import React,{useEffect,useState} from 'react';
import {Alert,ScrollView,Text,TextInput,TouchableOpacity,View} from 'react-native';
import {api} from './apiClient';

const Btn=({children,onPress,disabled})=><TouchableOpacity disabled={disabled} onPress={onPress} style={{backgroundColor:'#3f78ed',borderRadius:10,padding:10,marginRight:6,marginBottom:6}}><Text style={{color:'#fff',fontWeight:'900'}}>{children}</Text></TouchableOpacity>;
const Input=({value,onChangeText,placeholder})=><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#6f7888" style={{backgroundColor:'#11151c',borderWidth:1,borderColor:'#303a4a',borderRadius:10,color:'#fff',padding:10,marginBottom:7}}/>;

export default function AdminFleetPanel(){
 const [tab,setTab]=useState('vehicles'),[vehicles,setVehicles]=useState([]),[phones,setPhones]=useState([]),[assignments,setAssignments]=useState([]),[registration,setRegistration]=useState(''),[phoneName,setPhoneName]=useState(''),[newToken,setNewToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const [v,p,a]=await Promise.all([api('/vehicles'),api('/phones'),api('/assignments')]);setVehicles(v.vehicles||[]);setPhones(p.phones||[]);setAssignments(a.assignments||[]);setError('');}catch(e){setError(e.message||'Nie udało się pobrać floty.');}};
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t);},[]);
 const addVehicle=async()=>{if(!registration.trim())return;setBusy(true);try{await api('/vehicles',{method:'POST',body:{registration:registration.trim()}});setRegistration('');await load();}catch(e){setError(e.message||'Nie udało się dodać auta.');}finally{setBusy(false);}};
 const addPhone=async()=>{if(!phoneName.trim())return;setBusy(true);try{const r=await api('/phones',{method:'POST',body:{name:phoneName.trim()}});setPhoneName('');setNewToken(r.deviceToken||'');await load();}catch(e){setError(e.message||'Nie udało się dodać telefonu.');}finally{setBusy(false);}};
 const assign=async(v,p)=>{setBusy(true);try{await api('/assignments',{method:'POST',body:{vehicleId:v.id,phoneId:p.id}});await load();}catch(e){setError(e.message||'Nie udało się przypisać telefonu.');}finally{setBusy(false);}};
 const removeVehicle=async v=>{Alert.alert('Usuń auto','Usunąć '+v.registration+'?', [{text:'Anuluj',style:'cancel'},{text:'USUŃ',style:'destructive',onPress:async()=>{try{await api('/vehicles/'+v.id,{method:'DELETE'});await load();}catch(e){setError(e.message||'Błąd usuwania.');}}}]);};
 const removePhone=async p=>{Alert.alert('Usuń telefon','Usunąć '+p.name+'? Przypisanie do auta zostanie usunięte.',[{text:'Anuluj',style:'cancel'},{text:'USUŃ',style:'destructive',onPress:async()=>{setBusy(true);try{await api('/phones/'+p.id,{method:'DELETE'});setNewToken('');await load();}catch(e){setError(e.message||'Błąd usuwania telefonu.');}finally{setBusy(false);}}}]);};
 return <View style={{marginTop:16}}>
  <Text style={{color:'#fff',fontSize:19,fontWeight:'900'}}>🚗 Flota i telefony GPS</Text>
  <Text style={{color:'#9299a8',fontSize:13,marginTop:3,marginBottom:10}}>Centralne przypisanie: samochód → telefon → użytkownik.</Text>
  <View style={{flexDirection:'row',flexWrap:'wrap',marginBottom:8}}>{[['vehicles','🚗 SAMOCHODY'],['phones','📱 TELEFONY'],['assign','🔗 PRZYPISANIA']].map(([k,t])=><TouchableOpacity key={k} onPress={()=>setTab(k)} style={{backgroundColor:tab===k?'#3f78ed':'#252b35',borderRadius:10,padding:10,marginRight:6,marginBottom:6}}><Text style={{color:'#fff',fontWeight:'900'}}>{t}</Text></TouchableOpacity>)}</View>
  {!!error&&<Text style={{color:'#ff8a8a',marginBottom:8}}>⚠️ {error}</Text>}
  {tab==='vehicles'&&<><Input value={registration} onChangeText={setRegistration} placeholder="Numer rejestracyjny, np. DSW12345"/><Btn onPress={addVehicle} disabled={busy}>＋ DODAJ SAMOCHÓD</Btn>{vehicles.map(v=><View key={v.id} style={{backgroundColor:'#1c2029',borderRadius:12,padding:12,marginBottom:7,flexDirection:'row',alignItems:'center'}}><View style={{flex:1}}><Text style={{color:'#fff',fontWeight:'900'}}>{v.registration}</Text><Text style={{color:'#9299a8',fontSize:12}}>{v.active?'AKTYWNY':'NIEAKTYWNY'}</Text></View><TouchableOpacity onPress={()=>removeVehicle(v)}><Text style={{color:'#ff8a8a',fontWeight:'900'}}>🗑️</Text></TouchableOpacity></View>)}</>}
  {tab==='phones'&&<><Input value={phoneName} onChangeText={setPhoneName} placeholder="Nazwa telefonu, np. Iveco 01"/><Btn onPress={addPhone} disabled={busy}>＋ DODAJ TELEFON</Btn>{!!newToken&&<View style={{backgroundColor:'#253b2f',borderRadius:12,padding:12,marginBottom:8}}><Text style={{color:'#b7f0c8',fontWeight:'900'}}>TOKEN URZĄDZENIA</Text><Text selectable style={{color:'#fff',fontSize:12,marginTop:6}}>{newToken}</Text><Text style={{color:'#9fc6aa',fontSize:11,marginTop:5}}>Zapisz go na służbowym telefonie. Token jest pokazany tylko po utworzeniu telefonu.</Text></View>}{phones.map(p=><View key={p.id} style={{backgroundColor:'#1c2029',borderRadius:12,padding:12,marginBottom:7}}><Text style={{color:'#fff',fontWeight:'900'}}>📱 {p.name}</Text><Text style={{color:'#9299a8',fontSize:12}}>{p.active?'AKTYWNY':'NIEAKTYWNY'} · ostatnio: {p.last_seen_at?new Date(p.last_seen_at).toLocaleString('pl-PL'):'brak'}</Text><TouchableOpacity disabled={busy} onPress={()=>removePhone(p)} style={{alignSelf:'flex-end',marginTop:7}}><Text style={{color:'#ff8a8a',fontWeight:'900'}}>🗑️ USUŃ TELEFON</Text></TouchableOpacity></View>)}</>}
  {tab==='assign'&&<>{vehicles.map(v=><View key={v.id} style={{backgroundColor:'#1c2029',borderRadius:12,padding:12,marginBottom:8}}><Text style={{color:'#fff',fontWeight:'900'}}>🚗 {v.registration}</Text><Text style={{color:'#9299a8',fontSize:12,marginBottom:6}}>{assignments.find(a=>a.vehicle_id===v.id)?.phone_name||'Brak telefonu'}</Text><ScrollView horizontal>{phones.map(p=><Btn key={p.id} onPress={()=>assign(v,p)} disabled={busy}>📱 {p.name}</Btn>)}</ScrollView></View>)}</>}
 </View>;
}
