import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Linking,Modal,Platform,ScrollView,Text,TouchableOpacity,View} from 'react-native';
import {api,apiGetGps} from './apiClient';
import {WebView} from 'react-native-webview';
import useSecondTicker from './hooks/useSecondTicker';

const normalizeVehicleId=v=>String(v||'').trim().toUpperCase().replace(/[^A-Z0-9ĄĆĘŁŃÓŚŹŻ]+/gi,'_').slice(0,40);
const millis=v=>typeof v==='number'?v:typeof v==='string'?Date.parse(v)||0:typeof v?.toMillis==='function'?v.toMillis():0;
const speedKmh=p=>Math.max(0,Number(p?.speed)||0)*3.6;
const valid=p=>Number.isFinite(Number(p?.latitude))&&Number.isFinite(Number(p?.longitude))&&Number(p.latitude)>=-90&&Number(p.latitude)<=90&&Number(p.longitude)>=-180&&Number(p.longitude)<=180;
const dist=(a,b)=>{const R=6371000,p1=Number(a.latitude)*Math.PI/180,p2=Number(b.latitude)*Math.PI/180,dp=(Number(b.latitude)-Number(a.latitude))*Math.PI/180,dl=(Number(b.longitude)-Number(a.longitude))*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
const pointTime=p=>millis(p?.updatedAt??p?.observed_at);\nconst movementKmh=(p,prev)=>{const measured=speedKmh(p);if(measured>5)return measured;if(!prev)return measured;const elapsed=pointTime(p)-pointTime(prev);if(elapsed<=0||elapsed>180000)return measured;const moved=dist(p,prev);return moved>=30?Math.max(measured,moved/elapsed*3600):measured;};
const ordered=rows=>(rows||[]).filter(valid).slice().sort((a,b)=>pointTime(a)-pointTime(b));
const durationText=ms=>{const n=Math.max(0,Math.floor(ms/60000));return n<1?'krócej niż minutę':n<60?n+' min':Math.floor(n/60)+' godz. '+n%60+' min';};
const ageText=ts=>{const m=Math.max(0,Math.floor((Date.now()-millis(ts))/60000));return m<1?'przed chwilą':m<60?m+' min temu':Math.floor(m/60)+' h '+m%60+' min temu';};
function timeline(rows){const out=[];let previousPoint=null;for(const p of ordered(rows)){const pointSpeed=movementKmh(p,previousPoint);previousPoint=p;const type=pointSpeed>5?'drive':'stop',t=pointTime(p),prev=out[out.length-1],gap=prev?t-prev.end:Infinity,distFromPrev=prev?dist(prev.last,p):Infinity;if(prev&&prev.type===type&&gap>=0&&gap<=180000&&distFromPrev<=(type==='drive'?150:100)){prev.last=p;prev.end=t;prev.count++;prev.lat+=(Number(p.latitude)-prev.lat)/prev.count;prev.lon+=(Number(p.longitude)-prev.lon)/prev.count;prev.maxSpeed=Math.max(prev.maxSpeed,speedKmh(p));}else out.push({type,start:t,end:t,first:p,last:p,count:1,lat:Number(p.latitude),lon:Number(p.longitude),maxSpeed:speedKmh(p)});}return out.reverse();}
const geocode=async p=>{const lat=Number(p?.latitude),lon=Number(p?.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;try{const r=await fetch('https://api.bigdatacloud.net/data/reverse-geocode-client?latitude='+lat+'&longitude='+lon+'&localityLanguage=pl');if(r.ok){const d=await r.json(),v=[d.city||d.locality||d.principalSubdivision,d.localityInfo?.informative?.find(x=>/street|road|ulica|droga/i.test(x.description||''))?.name].filter(Boolean).join(', ');if(v)return v;}}catch{}return null;};
const payloadFor=(location,history)=>{const points=[];let previous=null;for(const p of ordered(history)){points.push({lat:Number(p.latitude),lon:Number(p.longitude),speed:movementKmh(p,previous),time:pointTime(p)});previous=p;}return {location:location&&valid(location)?{lat:Number(location.latitude),lon:Number(location.longitude),speed:speedKmh(location),time:millis(location.updatedAt)}:null,points};};
const jsonSafe=v=>JSON.stringify(v).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');
const mapDocument=initial=>`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#map{height:100%;width:100%;margin:0;background:#11151c}.legend{background:#141922;color:#fff;padding:8px;border-radius:8px;font:12px Arial}</style></head><body><div id="map"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const map=L.map('map').setView([51.1,17],8);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);const layer=L.layerGroup().addTo(map);let marker=null,centered=false;const c=L.control({position:'bottomleft'});c.onAdd=()=>{const e=L.DomUtil.create('div','legend');e.textContent='🔵 Trasa · 🟠 Postój · 🚚 Pozycja live';return e;};c.addTo(map);
function draw(d){if(!d)return;layer.clearLayers();const pts=d.points||[];let run=[];function flush(){if(run.length>1)L.polyline(run,{color:'#2878ff',weight:5,opacity:.9}).addTo(layer);run=[];}for(let i=0;i<pts.length;i++){const p=pts[i],prev=pts[i-1];if(p.speed>5){if(prev&&prev.speed>5&&p.time-prev.time<=180000)run.push([p.lat,p.lon]);else{flush();run.push([p.lat,p.lon]);}}else flush();}flush();let stops=[];function flushStop(){if(stops.length>=2){const p=stops[Math.floor(stops.length/2)];L.circleMarker([p.lat,p.lon],{radius:5,color:'#f59e0b',fillColor:'#f59e0b',fillOpacity:.9}).bindPopup('Postój: '+new Date(stops[0].time).toLocaleString('pl-PL')+' – '+new Date(stops[stops.length-1].time).toLocaleString('pl-PL')).addTo(layer);}stops=[];}for(const p of pts){const last=stops[stops.length-1];if(p.speed<=5){if(last&&p.time-last.time>180000)flushStop();stops.push(p);}else flushStop();}flushStop();if(d.location){const p=d.location,ll=[p.lat,p.lon];if(!marker)marker=L.marker(ll).addTo(map);else marker.setLatLng(ll);marker.bindPopup('Aktualna pozycja · '+Math.round(p.speed)+' km/h');if(!centered||!map.getBounds().contains(ll)){map.setView(ll,Math.max(13,map.getZoom()),{animate:false});centered=true;}}else if(pts.length&&!centered){map.fitBounds(L.latLngBounds(pts.map(p=>[p.lat,p.lon])),{padding:[20,20]});centered=true;}}
window.drawGps=draw;draw(${jsonSafe(initial)});function receive(e){try{const d=typeof e.data==='string'?JSON.parse(e.data):e.data;if(d?.type==='gps-update')draw(d.payload);}catch(_){}}window.addEventListener('message',receive);document.addEventListener('message',receive);
</script></body></html>`;

export default function LiveLocationDashboard({vehicleRegistration='',warehouseGeo={},reportHistory=[],onApplySuggestion}){
 const [location,setLocation]=useState(null),[history,setHistory]=useState([]),[error,setError]=useState(''),[address,setAddress]=useState('Ustalanie adresu…'),[selected,setSelected]=useState(null);
 const mapRef=useRef(null),tick=useSecondTicker(10000);
 const load=useCallback(async()=>{try{const vehicles=await apiGetGps(),requested=normalizeVehicleId(vehicleRegistration),v=vehicles.filter(x=>requested?normalizeVehicleId(x.registration||x.id)===requested:true).sort((a,b)=>millis(b.observed_at)-millis(a.observed_at))[0];if(!v){setError('Brak nowej pozycji z API. Zachowuję ostatnią znaną.');return;}const point={...v,updatedAt:v.observed_at};setLocation(point);const h=await api('/gps/'+encodeURIComponent(v.id)+'/history');setHistory(ordered((h.history||[]).map(p=>({...p,updatedAt:p.observed_at}))));setError(Date.now()-millis(point.updatedAt)>180000?'Ostatnia pozycja jest starsza niż 3 minuty.':'');}catch(e){setError(e?.status===401?'Brak autoryzacji API.':'Błąd połączenia. Zachowuję ostatnią znaną pozycję.');}},[vehicleRegistration]);
 useEffect(()=>{load();},[load,tick]);
 useEffect(()=>{let cancelled=false;if(!location){setAddress('Brak adresu lokalizacji');return;}setAddress('Ustalanie adresu…');const t=setTimeout(async()=>{const a=await geocode(location);if(!cancelled)setAddress(a||'Nie udało się ustalić adresu');},350);return()=>{cancelled=true;clearTimeout(t);};},[location?.latitude,location?.longitude]);
 const mapData=useMemo(()=>payloadFor(location,history),[location,history]),mapHtml=useMemo(()=>mapDocument({location:null,points:[]}),[]);
 const sendMap=useCallback(()=>mapRef.current?.postMessage(jsonSafe({type:'gps-update',payload:mapData})),[mapData]);
 useEffect(()=>{sendMap();},[sendMap]);
 const segments=useMemo(()=>timeline(history),[history]),warehouses=Object.entries(warehouseGeo||{}).map(([name,v])=>({name,...v}));
 const nearest=useMemo(()=>location?warehouses.filter(w=>Number.isFinite(Number(w.latitude))&&Number.isFinite(Number(w.longitude))).map(w=>({...w,distance:dist(location,w)})).sort((a,b)=>a.distance-b.distance)[0]||null:null,[location,warehouseGeo]);
 const speed=location?Math.round(speedKmh(location)):0,stale=!location||Date.now()-millis(location.updatedAt)>180000,last=reportHistory?.[0];
 let suggestion=null;if(location&&!stale){if(nearest&&nearest.distance<=220){const prev=String(last?.status||''),status=['Czekam na rozładunek','Czekam na załadunek'].includes(prev)?prev:'Zaczynam pracę, jestem na miejscu',lastAt=millis(last?.createdAt||last?.timestamp||last?.time);if(!(prev===status&&lastAt&&Date.now()-lastAt<1800000))suggestion={status,warehouse:nearest.name,distance:Math.round(nearest.distance),text:String(location.registration||vehicleRegistration).toUpperCase()+' '+nearest.name+' '+status.toLowerCase()};}else if(speed>5&&String(last?.status||'')!=='W drodze')suggestion={status:'W drodze',from:'',to:'',text:String(location.registration||vehicleRegistration).toUpperCase()+' w drodze'};}
 const openMap=async(p=location)=>{if(!p)return;try{await Linking.openURL('https://www.openstreetmap.org/?mlat='+p.latitude+'&mlon='+p.longitude+'#map=15/'+p.latitude+'/'+p.longitude);}catch{}};
 return <ScrollView style={{flex:1,padding:12}} contentContainerStyle={{paddingBottom:130}}>
  <View style={styles.header}><Text style={styles.title}>📍 LOKALIZACJA LIVE</Text><Text style={styles.sub}>Pozycja i trasa odświeżane co 10 sekund</Text></View>
  <View style={styles.card}><Text style={styles.big}>{location?(stale?'🟠 NIEAKTUALNA':speed>5?'🚚 ONLINE · W RUCHU':'🅿️ ONLINE · POSTÓJ'):'🔴 BRAK SYGNAŁU'}</Text><Text style={styles.main}>{location?address:'Czekam na pierwszy punkt GPS…'}</Text>{location&&<Text style={styles.sub}>{Number(location.latitude).toFixed(5)+', '+Number(location.longitude).toFixed(5)}</Text>}{location&&<Text style={styles.sub}>Aktualizacja: {ageText(location.updatedAt)} · ±{Math.round(Number(location.accuracy||0))} m · {speed} km/h · {location.registration}</Text>}{!!error&&<Text style={styles.error}>⚠️ {error}</Text>}<TouchableOpacity style={styles.button} onPress={()=>openMap()}><Text style={styles.buttonText}>OTWÓRZ AKTUALNĄ POZYCJĘ W MAPACH</Text></TouchableOpacity></View>
  <View style={styles.card}><Text style={styles.section}>🗺️ MAPA LIVE · ZAPISANA TRASA</Text><Text style={styles.sub}>Niebieska linia — przejazd; pomarańczowe punkty — postoje; znacznik — bieżąca pozycja.</Text><View style={styles.mapWrap}>{location?(Platform.OS==='web'?<iframe title="Mapa GPS na żywo" style={{width:'100%',height:'100%',border:0}} srcDoc={mapDocument(mapData)}/>:<WebView ref={mapRef} originWhitelist={['*']} source={{html:mapHtml}} javaScriptEnabled domStorageEnabled onLoadEnd={sendMap} setSupportMultipleWindows={false} style={{flex:1,backgroundColor:'#11151c'}}/>):<Text style={styles.sub}>Mapa pojawi się po odebraniu pozycji GPS.</Text>}</View><Text style={styles.sub}>Zapisanych punktów: {history.length} · Historia do 7 dni</Text></View>
  <View style={styles.card}><Text style={styles.section}>🤖 SUGESTIA RAPORTU</Text>{suggestion?<><Text style={styles.suggestion}>{suggestion.text}</Text><TouchableOpacity style={styles.button} onPress={()=>onApplySuggestion&&onApplySuggestion(suggestion)}><Text style={styles.buttonText}>UŻYJ TEGO RAPORTU</Text></TouchableOpacity></>:<Text style={styles.sub}>Brak nowego statusu do zaproponowania albo ostatni raport już obejmuje ten stan.</Text>}</View>
  <View style={styles.card}><Text style={styles.section}>🏭 NAJBLIŻSZY MAGAZYN</Text><Text style={styles.main}>{nearest?nearest.name+' · '+Math.round(nearest.distance)+' m':'Brak skonfigurowanych stref GPS.'}</Text></View>
  <View style={styles.card}><Text style={styles.section}>🧭 POSTOJE I PRZEJAZDY · 7 DNI</Text>{segments.length?segments.slice(0,8).map(s=>{const stop=s.type==='stop',d=Math.max(0,s.end-s.start);return <TouchableOpacity key={s.start+'-'+s.type} style={styles.historyRow} onPress={()=>setSelected({...s,latitude:s.lat,longitude:s.lon,updatedAt:s.end,segmentType:s.type,segmentStartAt:s.start,segmentEndAt:s.end,segmentDuration:d})}><Text style={styles.history}>{stop?'🅿️ POSTÓJ':'🚚 PRZEJAZD'} · {durationText(d)}</Text><Text style={styles.historyHint}>{new Date(s.start).toLocaleString('pl-PL')} {d?'— '+new Date(s.end).toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'}):''} · {stop?'jeden wpis dla całego postoju':'maks. '+Math.round(s.maxSpeed)+' km/h'} ›</Text></TouchableOpacity>;}):<Text style={styles.sub}>Historia pojawi się po zapisaniu kolejnych punktów GPS.</Text>}</View>
  <Modal visible={!!selected} transparent animationType="slide" onRequestClose={()=>setSelected(null)}><View style={styles.modalBackdrop}><View style={styles.modalCard}><Text style={styles.section}>📍 SZCZEGÓŁY {selected?.segmentType==='stop'?'POSTOJU':selected?.segmentType==='drive'?'PRZEJAZDU':'PUNKTU GPS'}</Text>{selected&&<><Text style={styles.main}>{new Date(selected.segmentStartAt||millis(selected.updatedAt)).toLocaleString('pl-PL')}</Text>{selected.segmentEndAt&&<Text style={styles.sub}>Koniec: {new Date(selected.segmentEndAt).toLocaleString('pl-PL')} · Czas: {durationText(selected.segmentDuration||0)}</Text>}<Text style={styles.sub}>Prędkość: {Math.round(speedKmh(selected))} km/h · Dokładność: ±{Math.round(Number(selected.accuracy||0))} m</Text><Text style={styles.sub}>Współrzędne: {Number(selected.latitude).toFixed(6)}, {Number(selected.longitude).toFixed(6)}</Text><TouchableOpacity style={styles.button} onPress={()=>openMap(selected)}><Text style={styles.buttonText}>OTWÓRZ MIEJSCE NA MAPIE</Text></TouchableOpacity></>}<TouchableOpacity style={styles.closeButton} onPress={()=>setSelected(null)}><Text style={styles.buttonText}>ZAMKNIJ</Text></TouchableOpacity></View></View></Modal>
 </ScrollView>;
}
const styles={header:{backgroundColor:'#141922',borderRadius:20,padding:18,marginBottom:10,borderWidth:1,borderColor:'#303a4a'},title:{color:'#fff',fontSize:23,fontWeight:'900'},sub:{color:'#9ba3b3',fontSize:13,marginTop:5},error:{color:'#f0b35a',fontSize:13,marginTop:8,fontWeight:'800'},card:{backgroundColor:'#141922',borderRadius:18,padding:16,marginBottom:10,borderWidth:1,borderColor:'#303a4a'},big:{color:'#fff',fontSize:18,fontWeight:'900'},main:{color:'#fff',fontSize:17,fontWeight:'800',marginTop:8},section:{color:'#fff',fontSize:16,fontWeight:'900',marginBottom:7},suggestion:{color:'#75a1ff',fontSize:18,fontWeight:'900'},button:{backgroundColor:'#3f78ed',borderRadius:13,padding:13,alignItems:'center',marginTop:10},buttonText:{color:'#fff',fontWeight:'900'},history:{color:'#cbd2df',fontSize:13,marginTop:7,fontWeight:'800'},historyRow:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#303a4a'},historyHint:{color:'#75a1ff',fontSize:12,marginTop:4},mapWrap:{height:360,borderRadius:18,overflow:'hidden',backgroundColor:'#0d121b',borderWidth:1,borderColor:'#303a4a',alignItems:'center',justifyContent:'center',marginTop:10},modalBackdrop:{flex:1,backgroundColor:'rgba(0,0,0,0.78)',justifyContent:'center',padding:16},modalCard:{backgroundColor:'#141922',borderRadius:20,borderWidth:1,borderColor:'#303a4a',padding:16,maxHeight:'90%'},closeButton:{backgroundColor:'#303a4a',borderRadius:12,padding:12,alignItems:'center',marginTop:10}};
