import React,{useEffect,useMemo,useState} from 'react';
import {Linking,Platform,ScrollView,Text,TouchableOpacity,View} from 'react-native';
import {api,apiGetGps} from './apiClient';
import {WebView} from 'react-native-webview';
import useSecondTicker from './hooks/useSecondTicker';
const normalizeVehicleId=value=>String(value||'').trim().toUpperCase().replace(/[^A-Z0-9ĄĆĘŁŃÓŚŹŻ]+/gi,'_').slice(0,40);

const serverMillis=v=>{if(typeof v==='number')return v;if(typeof v==='string')return Date.parse(v)||0;if(typeof v?.toMillis==='function')return v.toMillis();return 0;};
const distanceMeters=(a,b)=>{if(!a||!b)return Infinity;const R=6371000,p1=a.latitude*Math.PI/180,p2=b.latitude*Math.PI/180,dp=(b.latitude-a.latitude)*Math.PI/180,dl=(b.longitude-a.longitude)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
const ageText=ts=>{const m=Math.max(0,Math.floor((Date.now()-serverMillis(ts))/60000));if(m<1)return 'przed chwilą';if(m<60)return m+' min temu';return Math.floor(m/60)+' h '+m%60+' min temu';};
const geocodeAddress=async point=>{const lat=Number(point?.latitude),lon=Number(point?.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return null;try{const res=await fetch('https://nominatim.openstreetmap.org/reverse?format=jsonv2&addressdetails=1&zoom=18&accept-language=pl&lat='+encodeURIComponent(lat)+'&lon='+encodeURIComponent(lon),{headers:{Accept:'application/json'}});if(!res.ok)return null;const a=(await res.json())?.address||{},locality=a.city||a.town||a.village||a.municipality||a.suburb||'',road=a.road||'',house=a.house_number||'';return locality&&road?locality+', '+road+(house?' '+house:''):road||locality||null;}catch{return null;}};
const mapHtml=loc=>{const lat=Number(loc?.latitude),lon=Number(loc?.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return '<!doctype html><html><body style="margin:0;background:#11151c"></body></html>';const safeLat=lat.toFixed(6),safeLon=lon.toFixed(6);return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#map{height:100%;width:100%;margin:0;padding:0;background:#11151c;overflow:hidden}.leaflet-control-attribution{font-size:9px}</style></head><body><div id="map"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const p=['+safeLat+','+safeLon+'];const map=L.map("map",{zoomControl:false,attributionControl:true}).setView(p,15);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(map);L.marker(p).addTo(map).bindPopup("Aktualna lokalizacja auta").openPopup();setTimeout(()=>map.invalidateSize(),250);</script></body></html>';};

export default function LiveLocationDashboard({vehicleRegistration='',warehouseGeo={},reportHistory=[],onApplySuggestion}){
 const [location,setLocation]=useState(null),[history,setHistory]=useState([]),[locationError,setLocationError]=useState(''),[locationAddress,setLocationAddress]=useState('Ustalanie adresu…');
 useSecondTicker(10000);
 const load=async()=>{try{const rows=await apiGetGps();const requested=normalizeVehicleId(vehicleRegistration);const selected=rows.filter(x=>requested?normalizeVehicleId(x.registration||x.id)===requested:true).sort((a,b)=>serverMillis(b.observed_at)-serverMillis(a.observed_at))[0]||null;if(!selected){setLocation(null);setHistory([]);setLocationError('Brak GPS dla przypisanego pojazdu.');return;}const point={...selected,updatedAt:selected.observed_at};setLocation(point);const h=await api('/gps/'+encodeURIComponent(selected.id)+'/history');setHistory((h.history||[]).map(x=>({...x,updatedAt:x.observed_at})));setLocationError(Date.now()-serverMillis(point.updatedAt)>180000?'Nadajnik istnieje, ale ostatnia pozycja jest starsza niż 3 minuty.':'');}catch(e){setLocation(null);setHistory([]);setLocationError(e?.status===401?'Zaloguj się do centralnego serwera.':'Nie można pobrać lokalizacji z centralnego API.');}};
 useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t);},[vehicleRegistration]);
 useEffect(()=>{let cancelled=false;if(!location){setLocationAddress('Brak adresu lokalizacji');return;}setLocationAddress('Ustalanie adresu…');const timer=setTimeout(async()=>{const address=await geocodeAddress(location);if(!cancelled)setLocationAddress(address||'Nie udało się ustalić adresu');},350);return()=>{cancelled=true;clearTimeout(timer);};},[location?.latitude?Math.round(Number(location.latitude)*10000):null,location?.longitude?Math.round(Number(location.longitude)*10000):null]);
 const warehouses=Object.entries(warehouseGeo||{}).map(([name,v])=>({name,...v}));
 const nearby=useMemo(()=>{if(!location)return null;return warehouses.filter(w=>w.latitude&&w.longitude).map(w=>({...w,distance:distanceMeters(location,w)})).sort((a,b)=>a.distance-b.distance)[0]||null;},[location,warehouseGeo]);
 const speed=location&&Number(location.speed)>0?Math.round(Number(location.speed)*3.6):0,stale=location?Date.now()-serverMillis(location.updatedAt)>180000:true,last=reportHistory?.[0];
 let suggestion=null;
 if(location&&!stale){if(nearby&&nearby.distance<=220){const prev=String(last?.status||'');const status=prev==='Czekam na rozładunek'||prev==='Czekam na załadunek'?prev:'Zaczynam pracę, jestem na miejscu';suggestion={status,warehouse:nearby.name,distance:Math.round(nearby.distance),text:String(location.registration||vehicleRegistration).toUpperCase()+' '+nearby.name+' '+status.toLowerCase()};}else if(speed>=8)suggestion={status:'W drodze',from:'',to:'',text:String(location.registration||vehicleRegistration).toUpperCase()+' w drodze'};}
 const openMap=async()=>{if(!location)return;try{await Linking.openURL('https://www.openstreetmap.org/?mlat='+location.latitude+'&mlon='+location.longitude+'#map=15/'+location.latitude+'/'+location.longitude);}catch{}};
 const historyRows=history.slice(0,6);
 return <ScrollView style={{flex:1,padding:12}} contentContainerStyle={{paddingBottom:130}}>
  <View style={styles.header}><Text style={styles.title}>📍 LOKALIZACJA LIVE</Text><Text style={styles.sub}>Telefon → centralny API → aplikacja</Text></View>
  <View style={styles.card}><Text style={styles.big}>{location?(stale?'🟠 NIEAKTUALNA':'🟢 ONLINE'):'🔴 BRAK SYGNAŁU'}</Text><Text style={styles.main}>{location?locationAddress:'Czekam na pierwszy punkt GPS…'}</Text>{location&&<Text style={styles.sub}>{Number(location.latitude).toFixed(5)+', '+Number(location.longitude).toFixed(5)}</Text>}{location&&<Text style={styles.sub}>Aktualizacja: {ageText(location.updatedAt)} · ±{Math.round(Number(location.accuracy||0))} m · {speed} km/h · {location.registration}</Text>}{!!locationError&&<Text style={styles.error}>⚠️ {locationError}</Text>}<TouchableOpacity style={styles.button} onPress={openMap}><Text style={styles.buttonText}>🗺️ OTWÓRZ MAPĘ</Text></TouchableOpacity></View>
  <View style={styles.card}><Text style={styles.section}>🤖 SUGESTIA RAPORTU</Text>{suggestion?<><Text style={styles.suggestion}>{suggestion.text}</Text><TouchableOpacity style={styles.button} onPress={()=>onApplySuggestion&&onApplySuggestion(suggestion)}><Text style={styles.buttonText}>📋 UŻYJ TEJ FORMUŁKI</Text></TouchableOpacity></>:<Text style={styles.sub}>Brak wystarczających danych.</Text>}</View>
  <View style={styles.card}><Text style={styles.section}>🏭 NAJBLIŻSZY MAGAZYN</Text><Text style={styles.main}>{nearby?nearby.name+' · '+Math.round(nearby.distance)+' m':'Brak skonfigurowanych stref GPS.'}</Text></View>
  <View style={styles.card}><Text style={styles.section}>🧭 HISTORIA TRASY · 7 DNI</Text>{historyRows.map((p,i)=><HistoryPoint key={i} point={p}/>)}</View>
  <View style={styles.mapWrap}>{location?(Platform.OS==='web'?<iframe title="mapa" style={{width:'100%',height:'100%',border:0}} srcDoc={mapHtml(location)}/>:<WebView key={Math.round(Number(location.latitude)*10000)+'_'+Math.round(Number(location.longitude)*10000)} originWhitelist={['*']} source={{html:mapHtml(location),baseUrl:'https://www.openstreetmap.org'}} javaScriptEnabled domStorageEnabled mixedContentMode="always" setSupportMultipleWindows={false} scrollEnabled={false} style={{flex:1,backgroundColor:'#11151c'}}/>):<Text style={styles.sub}>Mapa pojawi się po odebraniu lokalizacji.</Text>}</View>
 </ScrollView>;
}
function HistoryPoint({point}){const [address,setAddress]=useState('Ustalanie adresu…');useEffect(()=>{geocodeAddress(point).then(x=>setAddress(x||'Brak adresu'));},[point]);return <Text style={styles.history}>{new Date(serverMillis(point.updatedAt)).toLocaleString('pl-PL')} · {address} · {Number(point.speed||0)>0?Math.round(Number(point.speed)*3.6)+' km/h':'postój'}</Text>;}
const styles={header:{backgroundColor:'#141922',borderRadius:20,padding:18,marginBottom:10,borderWidth:1,borderColor:'#303a4a'},title:{color:'#fff',fontSize:23,fontWeight:'900'},sub:{color:'#9ba3b3',fontSize:13,marginTop:5},error:{color:'#f0b35a',fontSize:13,marginTop:8,fontWeight:'800'},card:{backgroundColor:'#141922',borderRadius:18,padding:16,marginBottom:10,borderWidth:1,borderColor:'#303a4a'},big:{color:'#fff',fontSize:18,fontWeight:'900'},main:{color:'#fff',fontSize:17,fontWeight:'800',marginTop:8},section:{color:'#fff',fontSize:16,fontWeight:'900',marginBottom:7},suggestion:{color:'#75a1ff',fontSize:18,fontWeight:'900'},button:{backgroundColor:'#3f78ed',borderRadius:13,padding:13,alignItems:'center',marginTop:10},buttonText:{color:'#fff',fontWeight:'900'},history:{color:'#cbd2df',fontSize:12,marginTop:7},mapWrap:{height:300,borderRadius:18,overflow:'hidden',backgroundColor:'#0d121b',borderWidth:1,borderColor:'#303a4a',alignItems:'center',justifyContent:'center',padding:10}};
